parameters:

    logger_configuration_node.class: Fuz\Framework\ConfigurationNode\LoggerConfigurationNode
    file_loader.class: Fuz\Framework\Service\FileLoader
    file_system.class: Fuz\Framework\Service\FileSystem

services:

    logger_configuration_node:
        class: %logger_configuration_node.class%
        arguments: []
        tags:
         - { name: configuration.node }

    file_loader:
        class: %file_loader.class%
        arguments: []

    file_system:
        class: %file_system.class%
        arguments: []
