imports:
    - { resource: configuration_nodes.yml }
    - { resource: string_loaders.yml }

parameters:
    file_loader.class: Fuz\Framework\Service\FileLoader
    file_system.class: Fuz\Framework\Service\FileSystem

services:

    file_loader:
        class: %file_loader.class%
        arguments: []

    file_system:
        class: %file_system.class%
        arguments: []
