parameters:
    yaml.string_loader.class: Fuz\Framework\StringLoader\YamlStringLoader
    xml.string_loader.class: Fuz\Framework\StringLoader\XmlStringLoader

services:

    yaml.string_loader:
        class: %yaml.string_loader.class%
        arguments: []
        tags:
         - { name: string.loader, supports: YML/YAML }

    xml.string_loader:
        class: %xml.string_loader.class%
        arguments: []
        tags:
         - { name: string.loader, supports: XML }

