parameters:
    app.oauth_user_provider.class: Fuz\AppBundle\Model\OAuthUserProvider
    hwi_oauth.account.connector: Fuz\AppBundle\Connect\AccountConnect
    app.daemon.class: Fuz\AppBundle\Component\Daemon

services:

    app.oauth_user_provider:
        class: %app.oauth_user_provider.class%
        arguments: [@session, @doctrine.orm.entity_manager]

    hwi_oauth.account.connector:
        class: %hwi_oauth.account.connector%

    app.daemon:
        class: %app.daemon.class%
        arguments: [@kernel]
