parameters:
    app.oauth_user_provider.class: Fuz\AppBundle\Model\OAuthUserProvider
    hwi_oauth.account.connector: Fuz\AppBundle\Connect\AccountConnect
    app.process_configuration.class: Fuz\AppBundle\Service\ProcessConfiguration
    app.form.fiddle.class: Fuz\AppBundle\Form\FiddleType
    app.run_fiddle.class: Fuz\AppBundle\Service\RunFiddle
    app.twig.debug_extension.class: Fuz\AppBundle\Twig\Extension\DebugExtension
    app.twig.safety_extension.class: Fuz\AppBundle\Twig\Extension\SafetyExtension
    app.twig.github_extension.class: Fuz\AppBundle\Twig\Extension\GitHubExtension
    app.twig.hash_extension.class: Fuz\AppBundle\Twig\Extension\HashExtension

services:

    app.oauth_user_provider:
        class: %app.oauth_user_provider.class%
        arguments: [@session, @doctrine.orm.entity_manager]

    hwi_oauth.account.connector:
        class: %hwi_oauth.account.connector%

    app.process_configuration:
        class: %app.process_configuration.class%
        arguments: [@logger, %process%, %kernel.environment%]
        tags:
            - { name: monolog.logger, channel: process_configuration }

    app.form.fiddle:
         class: %app.form.fiddle.class%
         arguments: [@app.process_configuration]
         tags:
            - { name: form.type, alias: FiddleType }

    app.run_fiddle:
         class: %app.run_fiddle.class%
         arguments: [@logger, @filesystem, @app.process_configuration, %process%]
         tags:
             - { name: monolog.logger, channel: run_fiddle }

    app.twig.debug_extension:
         class: %app.twig.debug_extension.class%
         arguments: []
         tags:
             - { name: twig.extension }

    app.twig.safety_extension:
         class: %app.twig.safety_extension.class%
         arguments: [%kernel.root_dir%]
         tags:
             - { name: twig.extension }

    app.twig.github_extension:
         class: %app.twig.github_extension.class%
         arguments: [%github_repository_root%]
         tags:
             - { name: twig.extension }

    app.twig.hash_extension:
         class: %app.twig.hash_extension.class%
         arguments: []
         tags:
             - { name: twig.extension }
