parameters:
    app.oauth_user_provider.class: Fuz\AppBundle\Model\OAuthUserProvider
    hwi_oauth.account.connector: Fuz\AppBundle\Connect\AccountConnect
    app.daemon.class: Fuz\AppBundle\Component\Daemon
    app.process_configuration.class: Fuz\AppBundle\Service\ProcessConfiguration
    app.form.fiddle.class: Fuz\AppBundle\Form\FiddleType

services:

    app.oauth_user_provider:
        class: %app.oauth_user_provider.class%
        arguments: [@session, @doctrine.orm.entity_manager]

    hwi_oauth.account.connector:
        class: %hwi_oauth.account.connector%

    app.daemon:
        class: %app.daemon.class%
        arguments: [@kernel]

    app.process_configuration:
        class: %app.process_configuration.class%
        arguments: [%process%, %kernel.environment%]

    app.form.fiddle:
         class: %app.form.fiddle.class%
         arguments: [@app.process_configuration]
         tags:
            - { name: form.type, alias: task }