parameters:
    fiddle_agent.class: Fuz\Process\Agent\FiddleAgent
    error_manager.class: Fuz\Process\Service\ErrorManager
    debug_manager.class: Fuz\Process\Service\DebugManager
    environment_manager.class: Fuz\Process\Service\EnvironmentManager
    shared_memory_manager.class: Fuz\Process\Service\SharedMemoryManager
    engine_manager.class: Fuz\Process\Service\EngineManager
    context_manager.class: Fuz\Process\Service\ContextManager
    template_manager.class: Fuz\Process\Service\TemplateManager
    execute_manager.class: Fuz\Process\Service\ExecuteManager
    compiled_manager.class: Fuz\Process\Service\CompiledManager

services:

    fiddle_agent:
        class: %fiddle_agent.class%
        arguments: [@error_manager]
        scope: prototype

    error_manager:
        class: %error_manager.class%
        arguments: []

    debug_manager:
        class: %debug_manager.class%
        arguments: [@file_system, %debug%, %environment%]

    environment_manager:
        class: %environment_manager.class%
        arguments: [@file_system, %debug%, %environment%, %fiddle%]

    shared_memory_manager:
        class: %shared_memory_manager.class%
        arguments: [@environment_manager, %fiddle%]

    engine_manager:
        class: %engine_manager.class%
        arguments: [@service_container, %fiddle%, %twig_sources%]

    context_manager:
        class: %context_manager.class%
        arguments: [@string_loader]

    template_manager:
        class: %template_manager.class%
        arguments: [@file_system, %fiddle%, %templates%]

    execute_manager:
        class: %execute_manager.class%
        arguments: [@file_system, @environment_manager, @engine_manager, @context_manager, @template_manager, %fiddle%]

    compiled_manager:
        class: %compiled_manager.class%
        arguments: [@file_system, @environment_manager, %fiddle%]
