logger:
    level: DEBUG
    max_files: 30
    name: app.log

environment:
    directory: %rootDir%/../environment/
    validation: ^[a-zA-Z0-9-]{4,16}$
    expiry: 24

debug:
    directory: %rootDir%/../debug/
    expiry: 720
