logger:
    level: DEBUG
    max_files: 30
    name: %env%.log

environment:
    directory: %environment_directory%
    validation: ^[a-zA-Z0-9-]{4,16}$
    expiry: 24

debug:
    allowed: %debug_allowed%
    directory: %root_dir%/../debug/
    expiry: 720
    context_file: context.srz

fiddle:
    file: fiddle.shr
    templates_dir: twig/
    compiled_dir: php/

templates:
    validation: ^[A-Za-z0-9-_]{1,16}\.twig$

twig_sources:
    directory: %root_dir%/twig/uncompressed
