logger:
    level: DEBUG
    max_files: 30
    name: app.log

environment:
    directory: %rootDir%/../environment/
    validation: ^[a-zA-Z0-9-]{4,16}$
    expiry: 24

debug:
    directory: %rootDir%/../debug/
    expiry: 720
    context_file: context.srz

fiddle:
    file: fiddle.shr
    templates_dir: twig/
    compiled_dir: php/

templates:
    validation: ^[A-Za-z0-9-_]{1,16}\.twig$

twig_engines:
    directory: %rootDir%/twig/uncompressed
