parameters:
    run_command.class: Fuz\Process\Command\RunCommand
    environment_configuration_node.class: Fuz\Process\ConfigurationNode\EnvironmentConfigurationNode
    debug_configuration_node.class: Fuz\Process\ConfigurationNode\DebugConfigurationNode
    error.class: Fuz\Process\Service\Error
    debug.class: Fuz\Process\Service\Debug
    core.class: Fuz\Process\Service\Core

services:

    run_command:
        class: %run_command.class%
        arguments: []
        tags:
            - { name: command }

    environment_configuration_node:
        class: %environment_configuration_node.class%
        arguments: []
        tags:
         - { name: configuration.node }

    debug_configuration_node:
        class: %debug_configuration_node.class%
        arguments: []
        tags:
         - { name: configuration.node }

    error:
        class: %error.class%
        arguments: []

    debug:
        class: %debug.class%
        arguments: []

    core:
        class: %core.class%
        arguments: []
