imports:
    - { resource: commands.yml }
    - { resource: configuration_nodes.yml }
    - { resource: twig_engines.yml }

parameters:
    context_helper.class: Fuz\Process\Helper\ContextHelper
    error_manager.class: Fuz\Process\Service\ErrorManager
    debug_manager.class: Fuz\Process\Service\DebugManager
    environment_manager.class: Fuz\Process\Service\EnvironmentManager
    context_manager.class: Fuz\Process\Service\ContextManager

services:

    context_helper:
        class: %context_helper.class%
        arguments: [@error_manager]

    error_manager:
        class: %error_manager.class%
        arguments: []

    debug_manager:
        class: %debug_manager.class%
        arguments: [@file_system, %debug%, %environment%]

    environment_manager:
        class: %environment_manager.class%
        arguments: [@file_system, @context_helper, %debug%, %environment%, %fiddle%]

    context_manager:
        class: %context_manager.class%
        arguments: [@context_helper, @string_loader]

