imports:
    - { resource: commands.yml }
    - { resource: configuration_nodes.yml }
    - { resource: twig_engines.yml }

parameters:
    fiddle_agent.class: Fuz\Process\Agent\FiddleAgent
    error_manager.class: Fuz\Process\Service\ErrorManager
    debug_manager.class: Fuz\Process\Service\DebugManager
    environment_manager.class: Fuz\Process\Service\EnvironmentManager
    engine_manager.class: Fuz\Process\Service\EngineManager
    context_manager.class: Fuz\Process\Service\ContextManager
    template_manager.class: Fuz\Process\Service\TemplateManager

services:

    fiddle_agent:
        class: %fiddle_agent.class%
        arguments: [@error_manager]
        scope: prototype

    error_manager:
        class: %error_manager.class%
        arguments: []

    debug_manager:
        class: %debug_manager.class%
        arguments: [@file_system, %debug%, %environment%]

    environment_manager:
        class: %environment_manager.class%
        arguments: [@file_system, %debug%, %environment%, %fiddle%]

    engine_manager:
        class: %engine_manager.class%
        arguments: [@service_container, %fiddle%, %twig_engines%]

    context_manager:
        class: %context_manager.class%
        arguments: [@string_loader]

    template_manager:
        class: %template_manager.class%
        arguments: [@file_system, %fiddle%, %templates%]

