parameters:
    run_command.class: Fuz\Process\Command\RunCommand
    environment_configuration_node.class: Fuz\Process\ConfigurationNode\EnvironmentConfigurationNode
    debug_configuration_node.class: Fuz\Process\ConfigurationNode\DebugConfigurationNode
    error_manager.class: Fuz\Process\Service\ErrorManager
    context_manager.class: Fuz\Process\Service\ContextManager
    debug_manager.class: Fuz\Process\Service\DebugManager
    environment_manager.class: Fuz\Process\Service\EnvironmentManager

services:

    run_command:
        class: %run_command.class%
        arguments: []
        tags:
            - { name: command }

    environment_configuration_node:
        class: %environment_configuration_node.class%
        arguments: []
        tags:
         - { name: configuration.node }

    debug_configuration_node:
        class: %debug_configuration_node.class%
        arguments: []
        tags:
         - { name: configuration.node }

    error_manager:
        class: %error_manager.class%
        arguments: []

    context_manager:
        class: %context_manager.class%
        arguments: [@error_manager]

    debug_manager:
        class: %debug_manager.class%
        arguments: [@file_system, %debug%, %environment%]

    environment_manager:
        class: %environment_manager.class%
        arguments: [@file_system, @context_manager, %debug%, %environment%]

