parameters:
    twig_engine.0_9_0.class: Fuz\Process\TwigEngine\TwigEngine_0_9_0
    twig_engine.1_16_2.class: Fuz\Process\TwigEngine\TwigEngine_1_16_2

services:

    twig_engine.0_9_0:
        class: %twig_engine.0_9_0.class%
        arguments: []
        tags:
         - { name: twig.engine, version: Twig-0.9.0 }

    twig_engine.1_16_2:
        class: %twig_engine.1_16_2.class%
        arguments: []
        tags:
         - { name: twig.engine, version: Twig-1.16.2 }
