parameters:
    twig_engine.0_9_0.class: Fuz\Process\TwigEngine\TwigEngine_0_9_0

services:

    twig_engine.0_9_0:
        class: %twig_engine.0_9_0.class%
        arguments: []
        tags:
         - { name: twig.engine, version: Twig-0.9.0 }
