
fuz_app_login:
    resource: "@FuzAppBundle/Controller/LoginController.php"
    type:     annotation
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

google_login:
    pattern: /login/check-google

facebook_login:
    pattern: /login/check-facebook

twitter_login:
    pattern: /login/check-twitter

sensio_login:
    pattern: /login/check-sensio-connect

fuz_app_browse:
    resource: "@FuzAppBundle/Controller/BrowseController.php"
    type:     annotation
    prefix:   /browse

fuz_app_article:
    resource: "@FuzAppBundle/Controller/ArticleController.php"
    type:     annotation
    prefix:   /article

fuz_app_fiddle:
    resource: "@FuzAppBundle/Controller/FiddleController.php"
    type:     annotation
    prefix:   /

