security:
    providers:
        oauth_provider:
             id: app.oauth_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            logout: true
            logout:
                path: /logout
                target: /
            oauth:
                resource_owners:
                    google: "/login/check-google"
                    facebook: "/login/check-facebook"
                    twitter: "/login/check-twitter"
                    sensio_connect: "/login/check-sensio-connect"
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                    service: app.oauth_user_provider
        default:
            anonymous: ~

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, role: ROLE_USER }
        - { path: ^/logout, role: ROLE_USER }

hwi_oauth:
    firewall_name: main
    connect:
        confirmation: false
    resource_owners:
        google:
            type: google
            client_id: %google_client_id%
            client_secret: %google_secret%
            scope: "profile"
        facebook:
            type: facebook
            client_id: %facebook_client_id%
            client_secret: %facebook_secret%
            scope: "public_profile"
        twitter:
            type: twitter
            client_id: %twitter_client_id%
            client_secret: %twitter_secret%
            scope: ""
        sensio_connect:
            type: sensio_connect
            client_id: %sensio_client_id%
            client_secret: %sensio_secret%
            scope: "SCOPE_PUBLIC"
